name: gtvm-hs
version: "0.5.0"
synopsis: "Various tools for reversing and using assets from Golden Time: Vivid Memories."
github: raehik/gtvm-hs
extra-source-files:
- README.md
- CHANGELOG.md

default-extensions:
- OverloadedStrings
- LambdaCase

dependencies:
- base
- bytestring
- text
- megaparsec
- mtl
- either
- directory
- unicode-show
- aeson
- aeson-pretty
- lens
- lzo
- filemanip
- yaml

library:
  source-dirs: src

executables:
  gtvm-hs:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gtvm-hs
    - optparse-applicative
