name: gtvm-hs
version: "0.8.0"
synopsis: "Various tools for reversing and using assets from Golden Time: Vivid Memories."
github: raehik/gtvm-hs
extra-source-files:
- README.md
- CHANGELOG.md

# mostly Alexis King's 2018 recommended defaults
# (most can be replaced with GHC 9.2's GHC2021 language extension
default-extensions:
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- LambdaCase
- DeriveGeneric
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveLift
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- StandaloneDeriving
- BangPatterns
- KindSignatures
- TypeOperators
- TypeApplications

# we do a little type tomfoolery
- DataKinds
- TypeFamilies
- UndecidableInstances
- StandaloneKindSignatures
- RankNTypes
- ScopedTypeVariables

dependencies:
- base
- bytestring
- text
- megaparsec ^>= 9.2.0 # for my binary number parsing additions
- mtl
- either
- directory
- unicode-show
- aeson
- aeson-pretty
- lzo
- filemanip
- yaml
- cassava
- utf8-string
- vector
- barbies
- text-latin1
- blake3
- memory
- optics
- generic-optics
#- compdata
- union
- world-peace

library:
  source-dirs: src

executables:
  gtvm-hs:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gtvm-hs
    - optparse-applicative
