name: gtvm-hs
version: 1.0.0
synopsis: "Various tools for reversing and using assets from Golden Time: Vivid Memories."
github: raehik/gtvm-hs
extra-source-files:
- README.md
- CHANGELOG.md

# raehik's extensions (GHC 9.2; last updated: 2022-10-09)
language: GHC2021
default-extensions:
# syntax that should be default
- LambdaCase
- NoStarIsType

## deriving-related
- DerivingVia # implies DerivingStrategies
- DeriveAnyClass

# features that should be default
- GADTs
- RoleAnnotations

# other features
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash

# useful extensions to know about, but which should be specified on-demand
#
# UndecidableInstances:
#   required for type class wizardry
#   generally only enable if you were expecting to & compilation fails without
# AllowAmbiguousTypes:
#   often goes hand in hand with TypeApplications-heavy code
#   enabling on demand brings attention to the sort of functions to expect
# StarIsType:
#   may need to enable if you're working with old code that uses `Int :: *`

ghc-options:
- -Wall

# omitting ticks is good; see https://gitlab.haskell.org/ghc/ghc/-/issues/20531
# (off by default since GHC 9.4)
- -Wno-unticked-promoted-constructors

dependencies:
- base >= 4.18 && < 5
- text >= 2.0.1 && < 2.2

# SCP
- binrep ^>= 1.0.0
- strongweak ^>= 0.9.1
- generic-data-functions ^>= 0.6.0
- symparsec ^>= 1.1.1
- aeson >= 2.1 && < 2.3

# SCPTL (TODO)
- mtl ^>= 2.3.1
- containers >= 0.6 && < 0.8 # TODO need to permit 0.6 for polysemy

# studio (TODO)
- polysemy ^>= 1.9.2.0 # TODO move to bluefin :)
- path ^>= 0.9.5
- yaml ^>= 0.11.11.2
- exceptions ^>= 0.10.7

# old (TODO)
#- directory
#- unicode-show
#- lzo
#- filemanip
#- cassava
#- barbies
#- text-latin1
#- blake3
#- memory
#- optics
#- generic-optics
#- filepath
#- unordered-containers
#- aeson-pretty

library:
  source-dirs: src

executables:
  gtvm-hs:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gtvm-hs
    - optparse-applicative ^>= 0.18.1.0
    - yaml ^>= 0.11.11.2
    - rerefined ^>= 0.6.0
    - bytestring >= 0.11 && < 0.13
