name: gtvm-hs
version: "0.9.0"
synopsis: "Various tools for reversing and using assets from Golden Time: Vivid Memories."
github: raehik/gtvm-hs
extra-source-files:
- README.md
- CHANGELOG.md

# mostly Alexis King's 2018 recommended defaults
# (most can be replaced with GHC 9.2's GHC2021 language extension
default-extensions:
# essential
- EmptyCase
- FlexibleContexts
- FlexibleInstances
- InstanceSigs
- MultiParamTypeClasses
- PolyKinds
- LambdaCase
# deriving-related
- DerivingStrategies
- StandaloneDeriving
- DeriveAnyClass
- DeriveGeneric
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveLift
# essential syntax but too recent
- ImportQualifiedPost # 8.10
- StandaloneKindSignatures # 8.10
- DerivingVia # 8.6
# less essential but still gimmes
- RoleAnnotations
- TypeApplications
- DataKinds
- TypeFamilies
- TypeOperators
- BangPatterns
- GADTs
- DefaultSignatures
- RankNTypes
# extra
- UndecidableInstances # honestly fine but...
- MagicHash # pretty much syntactic, but too weird
- ScopedTypeVariables # probs dangerous to have as default

dependencies:
- base
- bytestring
- text
- megaparsec ^>= 9.2.0 # for my binary number parsing additions
- mtl
- transformers
- either
- directory
- unicode-show
- aeson
- lzo
- filemanip
- cassava
- utf8-string
- barbies
- text-latin1
- blake3
- memory
- optics
- generic-optics
- filepath
- containers
- algebraic-graphs
- hash-graph
- unordered-containers
- refined
- binrep ^>= 0.3.0
- vector-sized
- strongweak ^>= 0.3.0
- prettyprinter
#- aeson-pretty

# studio
- polysemy
- path
- yaml
- exceptions

ghc-options:
- -Wall

library:
  source-dirs: src

executables:
  gtvm-hs:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gtvm-hs
    - optparse-applicative
    - yaml
