name: gtvm

default-extensions:
- OverloadedStrings
- LambdaCase

dependencies:
- base
- bytestring
- text
- megaparsec
- mtl
- either
- directory
- unicode-show
- aeson
- aeson-pretty
- lens
  #- bytestring-strict-builder
  #- streaming
  #- streaming-bytestring >= 0.2.0
  #- containers
  #- recursion-schemes
  #- data-fix >= 0.3.0 # renames cata -> foldFix etc.
  #- free
  #- streaming-attoparsec
  #- attoparsec
  #- binary

library:
  source-dirs: src

executables:
  gtvm-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gtvm
    - optparse-applicative
