name: gtvm-hs
version: "0.9.0"
synopsis: "Various tools for reversing and using assets from Golden Time: Vivid Memories."
github: raehik/gtvm-hs
extra-source-files:
- README.md
- CHANGELOG.md

# raehik's extensions (GHC 9.2; last updated: 2022-10-09)
language: GHC2021
default-extensions:
# syntax that should be default
- LambdaCase
- NoStarIsType

## deriving-related
- DerivingVia # implies DerivingStrategies
- DeriveAnyClass

# features that should be default
- GADTs
- RoleAnnotations

# other features
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash

# useful extensions to know about, but which should be specified on-demand
#
# UndecidableInstances:
#   required for type class wizardry
#   generally only enable if you were expecting to & compilation fails without
# AllowAmbiguousTypes:
#   often goes hand in hand with TypeApplications-heavy code
#   enabling on demand brings attention to the sort of functions to expect
# StarIsType:
#   may need to enable if you're working with old code that uses `Int :: *`

ghc-options:
- -Wall

dependencies:
- base

- binrep
- bytezap
- refined
- strongweak
- rerefined

- bytestring
- text ^>= 2.0.1
- megaparsec ^>= 9.2.0 # for my binary number parsing additions
- mtl
- transformers
- either
- directory
- unicode-show
- aeson
- lzo
- filemanip
- cassava
- barbies
- text-latin1
- blake3
- memory
- optics
- generic-optics
- filepath
- containers
- unordered-containers
- vector-sized
- prettyprinter
#- aeson-pretty

# studio
- polysemy
- path
- yaml
- exceptions

library:
  source-dirs: src

executables:
  gtvm-hs:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gtvm-hs
    - optparse-applicative
    - yaml
